# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mo_info_pb2 as mo__info__pb2


class InformerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetParamsValuesForMO = channel.unary_unary(
                '/mo_info.Informer/GetParamsValuesForMO',
                request_serializer=mo__info__pb2.InfoRequest.SerializeToString,
                response_deserializer=mo__info__pb2.InfoReply.FromString,
                )
        self.GetTMOidForMo = channel.unary_unary(
                '/mo_info.Informer/GetTMOidForMo',
                request_serializer=mo__info__pb2.IntValue.SerializeToString,
                response_deserializer=mo__info__pb2.MOInfo.FromString,
                )
        self.GetObjWithParams = channel.unary_stream(
                '/mo_info.Informer/GetObjWithParams',
                request_serializer=mo__info__pb2.RequestForObjInfoByTMO.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseWithObjInfoByTMO.FromString,
                )
        self.GetFilteredObjWithParams = channel.unary_unary(
                '/mo_info.Informer/GetFilteredObjWithParams',
                request_serializer=mo__info__pb2.RequestForFilteredObjInfoByTMO.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseMOdata.FromString,
                )
        self.GetTMOlifecycle = channel.unary_unary(
                '/mo_info.Informer/GetTMOlifecycle',
                request_serializer=mo__info__pb2.RequestTMOlifecycleByTMOidList.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseTMOlifecycleByTMOidList.FromString,
                )
        self.GetMOSeverityMaxValue = channel.unary_unary(
                '/mo_info.Informer/GetMOSeverityMaxValue',
                request_serializer=mo__info__pb2.RequestSeverityMoId.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseSeverityMoId.FromString,
                )
        self.GetMOQuantityBySeverity = channel.unary_unary(
                '/mo_info.Informer/GetMOQuantityBySeverity',
                request_serializer=mo__info__pb2.RequestSeverityValues.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseMOQuantityBySeverity.FromString,
                )
        self.GetTPRMNames = channel.unary_unary(
                '/mo_info.Informer/GetTPRMNames',
                request_serializer=mo__info__pb2.RequestTPRMIds.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseTPRMNames.FromString,
                )
        self.GetFilteredObjSpecial = channel.unary_stream(
                '/mo_info.Informer/GetFilteredObjSpecial',
                request_serializer=mo__info__pb2.RequestForFilteredObjSpecial.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseMOdataSpecial.FromString,
                )
        self.GetHierarchyLevelChildren = channel.unary_unary(
                '/mo_info.Informer/GetHierarchyLevelChildren',
                request_serializer=mo__info__pb2.RequestListLevels.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseListNodes.FromString,
                )
        self.GetMODetailsWithTPRMNames = channel.unary_unary(
                '/mo_info.Informer/GetMODetailsWithTPRMNames',
                request_serializer=mo__info__pb2.RequestMODetailsWithTPRMNames.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseMODetailsWithTPRMNames.FromString,
                )
        self.GetColumnsForMaterializedView = channel.unary_unary(
                '/mo_info.Informer/GetColumnsForMaterializedView',
                request_serializer=mo__info__pb2.RequestTMOAttrsAndTypes.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseTMOAttrsAndTypes.FromString,
                )
        self.GetTMOInfoByTMOId = channel.unary_unary(
                '/mo_info.Informer/GetTMOInfoByTMOId',
                request_serializer=mo__info__pb2.TMOInfoRequest.SerializeToString,
                response_deserializer=mo__info__pb2.TMOInfoResponse.FromString,
                )
        self.GetTMOInfoByMOId = channel.unary_unary(
                '/mo_info.Informer/GetTMOInfoByMOId',
                request_serializer=mo__info__pb2.MOInfoRequest.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseListInt.FromString,
                )
        self.GetObjWithParamsLimited = channel.unary_stream(
                '/mo_info.Informer/GetObjWithParamsLimited',
                request_serializer=mo__info__pb2.RequestObjWithParamsLimited.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseObjWithParamsLimited.FromString,
                )
        self.GetTPRMData = channel.unary_unary(
                '/mo_info.Informer/GetTPRMData',
                request_serializer=mo__info__pb2.RequestTPRMData.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseTPRMData.FromString,
                )
        self.GetTPRMNameToTypeMapper = channel.unary_unary(
                '/mo_info.Informer/GetTPRMNameToTypeMapper',
                request_serializer=mo__info__pb2.RequestTPRMNameToType.SerializeToString,
                response_deserializer=mo__info__pb2.DeleteMOIdsResponse.FromString,
                )
        self.DeleteMOsByIds = channel.unary_unary(
                '/mo_info.Informer/DeleteMOsByIds',
                request_serializer=mo__info__pb2.DeleteMOIdsRequest.SerializeToString,
                response_deserializer=mo__info__pb2.DeleteMOIdsResponse.FromString,
                )
        self.GetAllTMO = channel.unary_unary(
                '/mo_info.Informer/GetAllTMO',
                request_serializer=mo__info__pb2.GetAllTMORequest.SerializeToString,
                response_deserializer=mo__info__pb2.GetAllTMOResponse.FromString,
                )
        self.GetAllMOWithParamsByTMOId = channel.unary_stream(
                '/mo_info.Informer/GetAllMOWithParamsByTMOId',
                request_serializer=mo__info__pb2.GetAllMOWithParamsByTMOIdRequest.SerializeToString,
                response_deserializer=mo__info__pb2.GetAllMOWithParamsByTMOIdResponse.FromString,
                )
        self.GetMODataByIds = channel.unary_stream(
                '/mo_info.Informer/GetMODataByIds',
                request_serializer=mo__info__pb2.GetMODataByIdsRequest.SerializeToString,
                response_deserializer=mo__info__pb2.GetMODataByIdsResponse.FromString,
                )
        self.GetPRMsByPRMIds = channel.unary_stream(
                '/mo_info.Informer/GetPRMsByPRMIds',
                request_serializer=mo__info__pb2.GetPRMsByPRMIdsRequest.SerializeToString,
                response_deserializer=mo__info__pb2.GetPRMsByPRMIdsResponse.FromString,
                )
        self.GetTPRMAllData = channel.unary_stream(
                '/mo_info.Informer/GetTPRMAllData',
                request_serializer=mo__info__pb2.RequestGetTPRMAlldata.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseGetTPRMAlldata.FromString,
                )
        self.GetAllTPRMSByTMOId = channel.unary_stream(
                '/mo_info.Informer/GetAllTPRMSByTMOId',
                request_serializer=mo__info__pb2.RequestGetAllTPRMSByTMOId.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseGetAllTPRMSByTMOId.FromString,
                )
        self.GetAllRawPRMDataByTPRMId = channel.unary_stream(
                '/mo_info.Informer/GetAllRawPRMDataByTPRMId',
                request_serializer=mo__info__pb2.RequestGetAllRawPRMDataByTPRMId.SerializeToString,
                response_deserializer=mo__info__pb2.ResponseGetAllRawPRMDataByTPRMId.FromString,
                )


class InformerServicer(object):
    """The greeting service definition.
    """

    def GetParamsValuesForMO(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTMOidForMo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjWithParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilteredObjWithParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTMOlifecycle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMOSeverityMaxValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMOQuantityBySeverity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTPRMNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilteredObjSpecial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHierarchyLevelChildren(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMODetailsWithTPRMNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetColumnsForMaterializedView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTMOInfoByTMOId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTMOInfoByMOId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjWithParamsLimited(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTPRMData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTPRMNameToTypeMapper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMOsByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTMO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMOWithParamsByTMOId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMODataByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPRMsByPRMIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTPRMAllData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTPRMSByTMOId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllRawPRMDataByTPRMId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InformerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetParamsValuesForMO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParamsValuesForMO,
                    request_deserializer=mo__info__pb2.InfoRequest.FromString,
                    response_serializer=mo__info__pb2.InfoReply.SerializeToString,
            ),
            'GetTMOidForMo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTMOidForMo,
                    request_deserializer=mo__info__pb2.IntValue.FromString,
                    response_serializer=mo__info__pb2.MOInfo.SerializeToString,
            ),
            'GetObjWithParams': grpc.unary_stream_rpc_method_handler(
                    servicer.GetObjWithParams,
                    request_deserializer=mo__info__pb2.RequestForObjInfoByTMO.FromString,
                    response_serializer=mo__info__pb2.ResponseWithObjInfoByTMO.SerializeToString,
            ),
            'GetFilteredObjWithParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilteredObjWithParams,
                    request_deserializer=mo__info__pb2.RequestForFilteredObjInfoByTMO.FromString,
                    response_serializer=mo__info__pb2.ResponseMOdata.SerializeToString,
            ),
            'GetTMOlifecycle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTMOlifecycle,
                    request_deserializer=mo__info__pb2.RequestTMOlifecycleByTMOidList.FromString,
                    response_serializer=mo__info__pb2.ResponseTMOlifecycleByTMOidList.SerializeToString,
            ),
            'GetMOSeverityMaxValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMOSeverityMaxValue,
                    request_deserializer=mo__info__pb2.RequestSeverityMoId.FromString,
                    response_serializer=mo__info__pb2.ResponseSeverityMoId.SerializeToString,
            ),
            'GetMOQuantityBySeverity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMOQuantityBySeverity,
                    request_deserializer=mo__info__pb2.RequestSeverityValues.FromString,
                    response_serializer=mo__info__pb2.ResponseMOQuantityBySeverity.SerializeToString,
            ),
            'GetTPRMNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTPRMNames,
                    request_deserializer=mo__info__pb2.RequestTPRMIds.FromString,
                    response_serializer=mo__info__pb2.ResponseTPRMNames.SerializeToString,
            ),
            'GetFilteredObjSpecial': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFilteredObjSpecial,
                    request_deserializer=mo__info__pb2.RequestForFilteredObjSpecial.FromString,
                    response_serializer=mo__info__pb2.ResponseMOdataSpecial.SerializeToString,
            ),
            'GetHierarchyLevelChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHierarchyLevelChildren,
                    request_deserializer=mo__info__pb2.RequestListLevels.FromString,
                    response_serializer=mo__info__pb2.ResponseListNodes.SerializeToString,
            ),
            'GetMODetailsWithTPRMNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMODetailsWithTPRMNames,
                    request_deserializer=mo__info__pb2.RequestMODetailsWithTPRMNames.FromString,
                    response_serializer=mo__info__pb2.ResponseMODetailsWithTPRMNames.SerializeToString,
            ),
            'GetColumnsForMaterializedView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetColumnsForMaterializedView,
                    request_deserializer=mo__info__pb2.RequestTMOAttrsAndTypes.FromString,
                    response_serializer=mo__info__pb2.ResponseTMOAttrsAndTypes.SerializeToString,
            ),
            'GetTMOInfoByTMOId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTMOInfoByTMOId,
                    request_deserializer=mo__info__pb2.TMOInfoRequest.FromString,
                    response_serializer=mo__info__pb2.TMOInfoResponse.SerializeToString,
            ),
            'GetTMOInfoByMOId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTMOInfoByMOId,
                    request_deserializer=mo__info__pb2.MOInfoRequest.FromString,
                    response_serializer=mo__info__pb2.ResponseListInt.SerializeToString,
            ),
            'GetObjWithParamsLimited': grpc.unary_stream_rpc_method_handler(
                    servicer.GetObjWithParamsLimited,
                    request_deserializer=mo__info__pb2.RequestObjWithParamsLimited.FromString,
                    response_serializer=mo__info__pb2.ResponseObjWithParamsLimited.SerializeToString,
            ),
            'GetTPRMData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTPRMData,
                    request_deserializer=mo__info__pb2.RequestTPRMData.FromString,
                    response_serializer=mo__info__pb2.ResponseTPRMData.SerializeToString,
            ),
            'GetTPRMNameToTypeMapper': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTPRMNameToTypeMapper,
                    request_deserializer=mo__info__pb2.RequestTPRMNameToType.FromString,
                    response_serializer=mo__info__pb2.DeleteMOIdsResponse.SerializeToString,
            ),
            'DeleteMOsByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMOsByIds,
                    request_deserializer=mo__info__pb2.DeleteMOIdsRequest.FromString,
                    response_serializer=mo__info__pb2.DeleteMOIdsResponse.SerializeToString,
            ),
            'GetAllTMO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTMO,
                    request_deserializer=mo__info__pb2.GetAllTMORequest.FromString,
                    response_serializer=mo__info__pb2.GetAllTMOResponse.SerializeToString,
            ),
            'GetAllMOWithParamsByTMOId': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllMOWithParamsByTMOId,
                    request_deserializer=mo__info__pb2.GetAllMOWithParamsByTMOIdRequest.FromString,
                    response_serializer=mo__info__pb2.GetAllMOWithParamsByTMOIdResponse.SerializeToString,
            ),
            'GetMODataByIds': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMODataByIds,
                    request_deserializer=mo__info__pb2.GetMODataByIdsRequest.FromString,
                    response_serializer=mo__info__pb2.GetMODataByIdsResponse.SerializeToString,
            ),
            'GetPRMsByPRMIds': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPRMsByPRMIds,
                    request_deserializer=mo__info__pb2.GetPRMsByPRMIdsRequest.FromString,
                    response_serializer=mo__info__pb2.GetPRMsByPRMIdsResponse.SerializeToString,
            ),
            'GetTPRMAllData': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTPRMAllData,
                    request_deserializer=mo__info__pb2.RequestGetTPRMAlldata.FromString,
                    response_serializer=mo__info__pb2.ResponseGetTPRMAlldata.SerializeToString,
            ),
            'GetAllTPRMSByTMOId': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllTPRMSByTMOId,
                    request_deserializer=mo__info__pb2.RequestGetAllTPRMSByTMOId.FromString,
                    response_serializer=mo__info__pb2.ResponseGetAllTPRMSByTMOId.SerializeToString,
            ),
            'GetAllRawPRMDataByTPRMId': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllRawPRMDataByTPRMId,
                    request_deserializer=mo__info__pb2.RequestGetAllRawPRMDataByTPRMId.FromString,
                    response_serializer=mo__info__pb2.ResponseGetAllRawPRMDataByTPRMId.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mo_info.Informer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Informer(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetParamsValuesForMO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetParamsValuesForMO',
            mo__info__pb2.InfoRequest.SerializeToString,
            mo__info__pb2.InfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTMOidForMo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetTMOidForMo',
            mo__info__pb2.IntValue.SerializeToString,
            mo__info__pb2.MOInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObjWithParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_info.Informer/GetObjWithParams',
            mo__info__pb2.RequestForObjInfoByTMO.SerializeToString,
            mo__info__pb2.ResponseWithObjInfoByTMO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFilteredObjWithParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetFilteredObjWithParams',
            mo__info__pb2.RequestForFilteredObjInfoByTMO.SerializeToString,
            mo__info__pb2.ResponseMOdata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTMOlifecycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetTMOlifecycle',
            mo__info__pb2.RequestTMOlifecycleByTMOidList.SerializeToString,
            mo__info__pb2.ResponseTMOlifecycleByTMOidList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMOSeverityMaxValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetMOSeverityMaxValue',
            mo__info__pb2.RequestSeverityMoId.SerializeToString,
            mo__info__pb2.ResponseSeverityMoId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMOQuantityBySeverity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetMOQuantityBySeverity',
            mo__info__pb2.RequestSeverityValues.SerializeToString,
            mo__info__pb2.ResponseMOQuantityBySeverity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTPRMNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetTPRMNames',
            mo__info__pb2.RequestTPRMIds.SerializeToString,
            mo__info__pb2.ResponseTPRMNames.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFilteredObjSpecial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_info.Informer/GetFilteredObjSpecial',
            mo__info__pb2.RequestForFilteredObjSpecial.SerializeToString,
            mo__info__pb2.ResponseMOdataSpecial.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHierarchyLevelChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetHierarchyLevelChildren',
            mo__info__pb2.RequestListLevels.SerializeToString,
            mo__info__pb2.ResponseListNodes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMODetailsWithTPRMNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetMODetailsWithTPRMNames',
            mo__info__pb2.RequestMODetailsWithTPRMNames.SerializeToString,
            mo__info__pb2.ResponseMODetailsWithTPRMNames.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetColumnsForMaterializedView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetColumnsForMaterializedView',
            mo__info__pb2.RequestTMOAttrsAndTypes.SerializeToString,
            mo__info__pb2.ResponseTMOAttrsAndTypes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTMOInfoByTMOId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetTMOInfoByTMOId',
            mo__info__pb2.TMOInfoRequest.SerializeToString,
            mo__info__pb2.TMOInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTMOInfoByMOId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetTMOInfoByMOId',
            mo__info__pb2.MOInfoRequest.SerializeToString,
            mo__info__pb2.ResponseListInt.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObjWithParamsLimited(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_info.Informer/GetObjWithParamsLimited',
            mo__info__pb2.RequestObjWithParamsLimited.SerializeToString,
            mo__info__pb2.ResponseObjWithParamsLimited.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTPRMData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetTPRMData',
            mo__info__pb2.RequestTPRMData.SerializeToString,
            mo__info__pb2.ResponseTPRMData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTPRMNameToTypeMapper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetTPRMNameToTypeMapper',
            mo__info__pb2.RequestTPRMNameToType.SerializeToString,
            mo__info__pb2.DeleteMOIdsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMOsByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/DeleteMOsByIds',
            mo__info__pb2.DeleteMOIdsRequest.SerializeToString,
            mo__info__pb2.DeleteMOIdsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllTMO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mo_info.Informer/GetAllTMO',
            mo__info__pb2.GetAllTMORequest.SerializeToString,
            mo__info__pb2.GetAllTMOResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllMOWithParamsByTMOId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_info.Informer/GetAllMOWithParamsByTMOId',
            mo__info__pb2.GetAllMOWithParamsByTMOIdRequest.SerializeToString,
            mo__info__pb2.GetAllMOWithParamsByTMOIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMODataByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_info.Informer/GetMODataByIds',
            mo__info__pb2.GetMODataByIdsRequest.SerializeToString,
            mo__info__pb2.GetMODataByIdsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPRMsByPRMIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_info.Informer/GetPRMsByPRMIds',
            mo__info__pb2.GetPRMsByPRMIdsRequest.SerializeToString,
            mo__info__pb2.GetPRMsByPRMIdsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTPRMAllData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_info.Informer/GetTPRMAllData',
            mo__info__pb2.RequestGetTPRMAlldata.SerializeToString,
            mo__info__pb2.ResponseGetTPRMAlldata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllTPRMSByTMOId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_info.Informer/GetAllTPRMSByTMOId',
            mo__info__pb2.RequestGetAllTPRMSByTMOId.SerializeToString,
            mo__info__pb2.ResponseGetAllTPRMSByTMOId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllRawPRMDataByTPRMId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_info.Informer/GetAllRawPRMDataByTPRMId',
            mo__info__pb2.RequestGetAllRawPRMDataByTPRMId.SerializeToString,
            mo__info__pb2.ResponseGetAllRawPRMDataByTPRMId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
