"""Initial migration

Revision ID: 3060811d39b7
Revises: 
Create Date: 2024-12-27 14:54:18.153295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3060811d39b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    op.create_table('template_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('parent_object_id', sa.Integer(), nullable=True),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('id != parent_object_id', name='check_parent_object'),
    sa.ForeignKeyConstraint(['parent_object_id'], ['template_object.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_object_id'), 'template_object', ['id'], unique=False)
    op.create_table('template_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_object_id', sa.Integer(), nullable=False),
    sa.Column('parameter_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('constraint', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('val_type', sa.String(), nullable=False),
    sa.Column('valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['template_object_id'], ['template_object.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_parameter_id'), 'template_parameter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_parameter_id'), table_name='template_parameter')
    op.drop_table('template_parameter')
    op.drop_index(op.f('ix_template_object_id'), table_name='template_object')
    op.drop_table('template_object')
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
