"""Initial db

Revision ID: 464995b13f80
Revises: 
Create Date: 2025-01-03 12:25:15.443749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "464995b13f80"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("object_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("modification_date", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column(
            "valid",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template")),
        schema="my_schema",
    )
    op.create_index(
        op.f("ix_my_schema_template_id"),
        "template",
        ["id"],
        unique=False,
        schema="my_schema",
    )
    op.create_table(
        "template_object",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("parent_object_id", sa.Integer(), nullable=True),
        sa.Column("object_type_id", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "valid",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "id != parent_object_id",
            name=op.f("ck_template_object_check_parent_object"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_object_id"],
            ["my_schema.template_object.id"],
            name=op.f("fk_template_object_parent_object_id_template_object"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["my_schema.template.id"],
            name=op.f("fk_template_object_template_id_template"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_object")),
        schema="my_schema",
    )
    op.create_index(
        op.f("ix_my_schema_template_object_id"),
        "template_object",
        ["id"],
        unique=False,
        schema="my_schema",
    )
    op.create_table(
        "template_parameter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_object_id", sa.Integer(), nullable=False),
        sa.Column("parameter_type_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("constraint", sa.String(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("val_type", sa.String(), nullable=False),
        sa.Column(
            "valid",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["template_object_id"],
            ["my_schema.template_object.id"],
            name=op.f(
                "fk_template_parameter_template_object_id_template_object"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_parameter")),
        schema="my_schema",
    )
    op.create_index(
        op.f("ix_my_schema_template_parameter_id"),
        "template_parameter",
        ["id"],
        unique=False,
        schema="my_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_my_schema_template_parameter_id"),
        table_name="template_parameter",
        schema="my_schema",
    )
    op.drop_table("template_parameter", schema="my_schema")
    op.drop_index(
        op.f("ix_my_schema_template_object_id"),
        table_name="template_object",
        schema="my_schema",
    )
    op.drop_table("template_object", schema="my_schema")
    op.drop_index(
        op.f("ix_my_schema_template_id"),
        table_name="template",
        schema="my_schema",
    )
    op.drop_table("template", schema="my_schema")
    # ### end Alembic commands ###
