"""Initial db

Revision ID: 5d6d957bcbdb
Revises: 
Create Date: 2025-01-09 17:15:06.494953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d6d957bcbdb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("modification_date", sa.DateTime(), nullable=False),
        sa.Column("object_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "valid",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template")),
    )
    op.create_index(op.f("ix_template_id"), "template", ["id"], unique=False)
    op.create_table(
        "template_object",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("parent_object_id", sa.Integer(), nullable=True),
        sa.Column("object_type_id", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "valid",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "id != parent_object_id",
            name=op.f("ck_template_object_check_parent_object"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_object_id"],
            ["template_object.id"],
            name=op.f("fk_template_object_parent_object_id_template_object"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["template.id"],
            name=op.f("fk_template_object_template_id_template"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_object")),
    )
    op.create_index(
        op.f("ix_template_object_id"), "template_object", ["id"], unique=False
    )
    op.create_table(
        "template_parameter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_object_id", sa.Integer(), nullable=False),
        sa.Column("parameter_type_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("constraint", sa.String(), nullable=True),
        sa.Column("val_type", sa.String(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "valid",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["template_object_id"],
            ["template_object.id"],
            name=op.f(
                "fk_template_parameter_template_object_id_template_object"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_parameter")),
    )
    op.create_index(
        op.f("ix_template_parameter_id"),
        "template_parameter",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_template_parameter_id"), table_name="template_parameter"
    )
    op.drop_table("template_parameter")
    op.drop_index(op.f("ix_template_object_id"), table_name="template_object")
    op.drop_table("template_object")
    op.drop_index(op.f("ix_template_id"), table_name="template")
    op.drop_table("template")
    # ### end Alembic commands ###
