"""Add index

Revision ID: c5e4fd2ae2c5
Revises: 8fe8aeb77055
Create Date: 2025-09-11 13:07:26.103025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5e4fd2ae2c5"
down_revision: Union[str, None] = "8fe8aeb77055"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_template_object_object_type_id"),
        "template_object",
        ["object_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_parameter_parameter_type_id"),
        "template_parameter",
        ["parameter_type_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_template_parameter_parameter_type_id"),
        table_name="template_parameter",
    )
    op.drop_index(
        op.f("ix_template_object_object_type_id"), table_name="template_object"
    )
    # ### end Alembic commands ###
