"""Add valid to model

Revision ID: b270efb5b299
Revises: fab964905f49
Create Date: 2024-12-24 11:29:20.667674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b270efb5b299'
down_revision: Union[str, None] = 'fab964905f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('valid', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('template_object', sa.Column('valid', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('template_parameter', sa.Column('val_type', sa.String(), nullable=False))
    op.add_column('template_parameter', sa.Column('valid', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_parameter', 'valid')
    op.drop_column('template_parameter', 'val_type')
    op.drop_column('template_object', 'valid')
    op.drop_column('template', 'valid')
    # ### end Alembic commands ###
