"""empty message

Revision ID: b319111c3a75
Revises: fab964905f49
Create Date: 2024-12-18 17:16:13.239382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b319111c3a75'
down_revision: Union[str, None] = 'fab964905f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_template_object', 'template_object', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_template_object', 'template_object', ['template_id', 'object_type_id'])
    # ### end Alembic commands ###
