"""empty message

Revision ID: b6eaa5905788
Revises: b319111c3a75
Create Date: 2024-12-26 12:27:46.236829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6eaa5905788'
down_revision: Union[str, None] = 'b319111c3a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('template_object_parent_object_id_fkey', 'template_object', type_='foreignkey')
    op.create_foreign_key(None, 'template_object', 'template_object', ['parent_object_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_object', type_='foreignkey')
    op.create_foreign_key('template_object_parent_object_id_fkey', 'template_object', 'template_object', ['parent_object_id'], ['id'])
    # ### end Alembic commands ###
