"""Add template, template_object, and template_parameter tables

Revision ID: fab964905f49
Revises: c9df31a8e483
Create Date: 2024-12-17 13:08:28.942391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab964905f49'
down_revision: Union[str, None] = 'c9df31a8e483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('parent_object_id', sa.Integer(), nullable=True),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.CheckConstraint('id != parent_object_id', name='check_parent_object'),
    sa.ForeignKeyConstraint(['parent_object_id'], ['template_object.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'object_type_id', name='uq_template_object')
    )
    op.create_index(op.f('ix_template_object_id'), 'template_object', ['id'], unique=False)
    op.create_table('template_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_object_id', sa.Integer(), nullable=False),
    sa.Column('parameter_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('constraint', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_object_id'], ['template_object.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_parameter_id'), 'template_parameter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_parameter_id'), table_name='template_parameter')
    op.drop_table('template_parameter')
    op.drop_index(op.f('ix_template_object_id'), table_name='template_object')
    op.drop_table('template_object')
    # ### end Alembic commands ###
