name: avataa-platform

# x-logging: &logging
#   logging:
#     driver: loki
#     options:
#       loki-url: http://loki:3100/loki/api/v1/push
#       loki-external-labels: job=dockerlogs,owner=avataa,environment=${PLATFORM_PROJECT_ENVIRONMENT:?}

x-logging: &logging
  logging:
    options:
      max-size: 100m

x-networks: &networks
  networks:
    - avataa-platform

x-restart: &restart
  restart: always

networks:
  avataa-platform:
    external: true


services:

  object-templates:
    <<: [*logging, *networks, *restart]
    image: ${REGISTRY_URL:?}/${PLATFORM_PROJECT_NAME:?}/ms/object-templates:${OBJECT_TEMPLATES_VERSION:?}
    container_name: object-templates
    # ports:
    #   - "8000:8000"
    #   - "50051:50051"
    expose:
      - "8000"
      # - "50051"
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/8000 || exit 1'"]
      interval: 3s
      timeout: 1s
      retries: 10
    hostname: object-templates
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 8000M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 50M

  object-templates-healthcheck:
    <<: *networks
    image: ${REGISTRY_URL:?}/${PLATFORM_PROJECT_NAME:?}/curl:${HEALTHCHECK_VERSION:?}
    container_name: object-templates-healthcheck
    depends_on:
      object-templates:
        condition: service_healthy
